### ISSUE TITLE
Log-log plots

### ISSUE THREAD

**Issue by GuiltyBystander** [F43nd1r/zachtronics-leaderboard-bot#228]
Not sure if this should be the default or a toggle, but I find log-log plots let you see a frontier better.  See the daily pareto graphs for examples.  Obvious down sides is if any metric can be 0 which I think can only be overlap instructions.

[zlbb chart](https://zlbb.faendir.com/puzzles/w2946683186/visualizer?visualizerFilter-w2946683186.showOnlyFrontier=true&visualizerConfig.mode=2D&visualizerConfig.x=a&visualizerConfig.y=i&visualizerFilter-w2946683186.modifiers.overlap=false)
vs
<img src="https://media.discordapp.net/attachments/909638277756243978/1111987221881421854/today.png" width="400" />

**Comment by 12345ieee** [comment]
I too would like to make one axis log for sc cycles, but last time faendir told me it was hard to do.

We need someone with frontend experience.

**Comment by F43nd1r** [comment]
What do I care about my silly chatter from yesterday? Implemented in [245a4d0](https://github.com/F43nd1r/zachtronics-leaderboard-bot/commit/245a4d06df17e7920d2f81bbc7a6a8e8a682842e)
